name: Serverless Deployment

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
    secrets:
      serverless_access_key:
        required: true

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Npm Install
        run: npm install
      
      - name: Deploy
        uses: serverless/github-action@v4
        with:
          args: deploy --stage ${{ inputs.stage }}
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.serverless_access_key }}
