name: Delivery

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Npm Install
        run: npm install

  deploy-to-aws:
    needs: build
    uses: ./.github/workflows/aws.yaml
    with:
      stage: dev
    secrets:
      serverless_access_key: ${{ secrets.SERVERLESS_ACCESS_KEY }}
