name: Pull Request

on:
  pull_request:

jobs:
  deploy-to-aws:
    uses: ./.github/workflows/aws.yaml
    with:
      stage: dev
    secrets:
      serverless_access_key: ${{ secrets.SERVERLESS_ACCESS_KEY }}


